"""Table Blocks Created

Revision ID: 176bea2747ef
Revises: e416cb380917
Create Date: 2026-01-18 02:57:13.530404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '176bea2747ef'
down_revision: Union[str, None] = 'e416cb380917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_index(op.f('ix_blocks_block_id'), 'blocks', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_block_id'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
