"""Update table artwork schedule

Revision ID: 33c89609a273
Revises: 7c97e07ffe76
Create Date: 2026-03-07 17:56:00.055674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c89609a273'
down_revision: Union[str, None] = '7c97e07ffe76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork_schedule', sa.Column('schedule_status', sa.String(length=15), nullable=False))
    op.add_column('artwork_schedule', sa.Column('schedule_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('artwork_schedule', 'schedule_time')
    op.drop_column('artwork_schedule', 'schedule_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork_schedule', sa.Column('schedule_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('artwork_schedule', sa.Column('schedule_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('artwork_schedule', 'schedule_at')
    op.drop_column('artwork_schedule', 'schedule_status')
    # ### end Alembic commands ###
