"""Crear tabla de artworks favoritos

Revision ID: 7c97e07ffe76
Revises: 176bea2747ef
Create Date: 2026-03-01 17:54:31.960319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c97e07ffe76'
down_revision: Union[str, None] = '176bea2747ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_user_favorites',
    sa.Column('artwork_user_favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('artwork_user_favorite_id')
    )
    op.create_index(op.f('ix_artwork_user_favorites_artwork_user_favorite_id'), 'artwork_user_favorites', ['artwork_user_favorite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_user_favorites_artwork_user_favorite_id'), table_name='artwork_user_favorites')
    op.drop_table('artwork_user_favorites')
    # ### end Alembic commands ###
