"""create notifications table

Revision ID: cdf134fa35b8
Revises: 60a9b3cf8827
Create Date: 2026-03-08 17:48:13.044613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdf134fa35b8'
down_revision: Union[str, None] = '60a9b3cf8827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emitter_id', sa.Integer(), nullable=False),
    sa.Column('receipter_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emitter_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['receipter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notifications_receipter', 'notifications', ['receipter_id'], unique=False)
    op.create_index('idx_notifications_receipter_created', 'notifications', ['receipter_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_receipter_read', 'notifications', ['receipter_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.drop_index('idx_artwork_schedule_pending', table_name='artwork_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_artwork_schedule_pending', 'artwork_schedule', ['schedule_status', 'schedule_at'], unique=False)
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index('idx_notifications_receipter_read', table_name='notifications')
    op.drop_index('idx_notifications_receipter_created', table_name='notifications')
    op.drop_index('idx_notifications_receipter', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
